#:schema node_modules/wrangler/config-schema.json
name = "sublink-worke"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "7b4f4e056cd94b009dc41ce4d2e59538" }
]
